language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ouspix/docker-react  -f Dockerfile.dev .

script:
    - docker run  -e CI=true ouspix/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react-test"
    env: "DockerReactTest-env"
    bucket_name: "elasticbeanstalk-eu-west-3-202914226316"
    bucket_path: "docker-react-test"
    on:
        branch: master
    acccess_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"